version: '3.9'
services:
  # MongoDB Database
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - migration_network

  # MongoDB Admin Interface
  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    ports:
      - "8081:8081"
    networks:
      - migration_network

  # PostgreSQL Database
  postgres-server:
    image: postgres:15
    container_name: postgres-server
    restart: always
    environment:
      - POSTGRES_DB=techtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ../postgresql:/docker-entrypoint-initdb.d
    networks:
      - migration_network

  # PostgreSQL Admin Interface
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres-server
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@techtest.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - migration_network

volumes:
  mongodb_data:
  postgresql_data:
  pgadmin_data:

networks:
  migration_network:
    driver: bridge
